sudo: false
language: node-js
before_install:
services:
  - redis-server
install:
  - npm install
  - npm install -g sails
before_script:
  - git clone http://github.com/gmod/jbserver
  - cd jbserver
  - npm install
  - npm install gmod/jblast
  - ./jbutil --setupdata
  - ./bin/blast_getBlast.js
  - ./bin/blast_downloadDb.js htgs.05
  - nohup sails lift --port 5001 > jbserver.log 2>&1 &
  - echo $! > save_pid.txt #save last process pid
  - cd ..
  - sleep 20
script:
  - npm test
  - wget http://localhost:5001/jbrowse
  - kill -9 `cat jbserver/save_pid.txt`
  - cat jbserver/jbserver.log
after_failure:
  
