dist: trusty
sudo: false
language: node_js
node_js:
  - "11"
before_install:
services:
  - redis-server
install:
before_script:
  - echo "******************** before_script ************************"
  - npm i -g npm@6.4.1
  - npm -v
  - node -v 
  - npm i -g sails@1.0.2
  - cd ..
  - pwd
  - git clone --depth=50 http://github.com/gmod/jbconnect
  - cd jbconnect
  - npm install
  - npm install enuggetry/blast-ncbi-tools
  - npm install enuggetry/faux-blastdb
  - npm install gmod/jblast-jbconnect-hook
#  - npm install gmod/jblast-jbconnect-hook
  - ./utils/blast_getBlastUtils.js 2.8.1
  - npm install @gmod/jbrowse@1.15.1
  - node ./utils/jb_setup.js
  - ls blastdb
  - ls blastbin
#  - nohup sails lift --port 5001 > jbconnect.log 2>&1 &
#  - echo $! > save_pid.txt #save last process pid
#  - cd ..
#  - sleep 20
script:
  - npm run jblast-coverage
after_success:
  - cd ../jblast-jbconnect-hook
  - ls ../jbconnect/coverage
  - cat ../jbconnect/coverage/lcov.info | ./node_modules/.bin/coveralls
  - cd ../jbconnect
  - ./node_modules/nyc/bin/nyc.js report
after_failure:
  - cat node_modules/@gmod/jbrowse/setup.log
  
