sudo: false
language: node-js
before_install:
install:
  - npm install
before_script:
  - ./bin/blast_getBlast.js
  - ./bin/blast_downloadDb.js htgs.05 
script:
  - npm test
after_failure:
  - cat JBrowse-1.x.x-dev/setup.log 
  - find JBrowse-1.x.x-dev/extlib/lib/perl5
  - cat JBrowse-1.x.x-dev/src/build-report.txt
